
/* Insertions for table course */

insert into course (id, courseName, deptId) values (1,'Accounting & Finance',2);
insert into course (id, courseName, deptId) values (2,'Aeronautical & Manufacturing Engineering',4);
insert into course (id, courseName, deptId) values (3,'Agriculture & Forestry',7);
insert into course (id, courseName, deptId) values (4,'American Studies',3);
insert into course (id, courseName, deptId) values (5,'Anatomy & Physiology',6);
insert into course (id, courseName, deptId) values (6,'Anthropology',7);
insert into course (id, courseName, deptId) values (7,'Archaeology',7);
insert into course (id, courseName, deptId) values (8,'Architecture',4);
insert into course (id, courseName, deptId) values (9,'Art & Design',1);
insert into course (id, courseName, deptId) values (10,'Aural & Oral Sciences',7);
insert into course (id, courseName, deptId) values (11,'Biological Sciences',7);
insert into course (id, courseName, deptId) values (12,'Building',4);
insert into course (id, courseName, deptId) values (13,'Business & Management Studies',2);
insert into course (id, courseName, deptId) values (14,'Celtic Studies',3);
insert into course (id, courseName, deptId) values (15,'Chemical Engineering',4);
insert into course (id, courseName, deptId) values (16,'Chemistry',7);
insert into course (id, courseName, deptId) values (17,'Civil Engineering',4);
insert into course (id, courseName, deptId) values (18,'Classics & Ancient History',3);
insert into course (id, courseName, deptId) values (19,'Communication & Media Studies',2);
insert into course (id, courseName, deptId) values (20,'Complementary Medicine',6);
insert into course (id, courseName, deptId) values (21,'Computer Science',5);
insert into course (id, courseName, deptId) values (22,'Counselling',6);
insert into course (id, courseName, deptId) values (23,'Creative Writing',1);
insert into course (id, courseName, deptId) values (24,'Criminology',7);
insert into course (id, courseName, deptId) values (25,'Dentistry',6);
insert into course (id, courseName, deptId) values (26,'Drama, Dance & Cinematics',1);
insert into course (id, courseName, deptId) values (27,'East & South Asian Studies',3);
insert into course (id, courseName, deptId) values (28,'Economics',2);
insert into course (id, courseName, deptId) values (29,'Education',8);
insert into course (id, courseName, deptId) values (30,'Electrical & Electronic Engineering',4);
insert into course (id, courseName, deptId) values (31,'English',3);
insert into course (id, courseName, deptId) values (32,'Fashion',1);
insert into course (id, courseName, deptId) values (33,'Film Making',1);
insert into course (id, courseName, deptId) values (34,'Food Science',7);
insert into course (id, courseName, deptId) values (35,'Forensic Science',7);
insert into course (id, courseName, deptId) values (36,'French',3);
insert into course (id, courseName, deptId) values (37,'Geography & Environmental Sciences',7);
insert into course (id, courseName, deptId) values (38,'Geology',7);
insert into course (id, courseName, deptId) values (39,'General Engineering',4);
insert into course (id, courseName, deptId) values (40,'German',3);
insert into course (id, courseName, deptId) values (41,'History',3);
insert into course (id, courseName, deptId) values (42,'History of Art, Architecture & Design',1);
insert into course (id, courseName, deptId) values (43,'Hospitality, Leisure, Recreation & Tourism',2);
insert into course (id, courseName, deptId) values (44,'Iberian Languages/Hispanic Studies',3);
insert into course (id, courseName, deptId) values (45,'Italian',3);
insert into course (id, courseName, deptId) values (46,'Land & Property Management',2);
insert into course (id, courseName, deptId) values (47,'Law',2);
insert into course (id, courseName, deptId) values (48,'Librarianship & Information Management',5);
insert into course (id, courseName, deptId) values (49,'Linguistics',3);
insert into course (id, courseName, deptId) values (50,'Marketing',2);
insert into course (id, courseName, deptId) values (51,'Materials Technology',4);
insert into course (id, courseName, deptId) values (52,'Mathematics',7);
insert into course (id, courseName, deptId) values (53,'Mechanical Engineering',4);
insert into course (id, courseName, deptId) values (54,'Medical Technology',6);
insert into course (id, courseName, deptId) values (55,'Medicine',6);
insert into course (id, courseName, deptId) values (56,'Middle Eastern & African Studies',3);
insert into course (id, courseName, deptId) values (57,'Music',1);
insert into course (id, courseName, deptId) values (58,'Nursing',6);
insert into course (id, courseName, deptId) values (59,'Occupational Therapy',6);
insert into course (id, courseName, deptId) values (60,'Optometry, Ophthalmology & Orthoptics',6);
insert into course (id, courseName, deptId) values (61,'Pharmacology & Pharmacy',6);
insert into course (id, courseName, deptId) values (62,'Philosophy',3);
insert into course (id, courseName, deptId) values (63,'Physics and Astronomy',7);
insert into course (id, courseName, deptId) values (64,'Physiotherapy',6);
insert into course (id, courseName, deptId) values (65,'Politics',3);
insert into course (id, courseName, deptId) values (66,'Psychology',6);
insert into course (id, courseName, deptId) values (67,'Robotics',5);
insert into course (id, courseName, deptId) values (68,'Russian & East European Languages',3);
insert into course (id, courseName, deptId) values (69,'Social Policy',8);
insert into course (id, courseName, deptId) values (70,'Social Work',8);
insert into course (id, courseName, deptId) values (71,'Sociology',8);
insert into course (id, courseName, deptId) values (72,'Sports Science',6);
insert into course (id, courseName, deptId) values (73,'Theology & Religious Studies',3);
insert into course (id, courseName, deptId) values (74,'Veterinary Medicine',6);
insert into course (id, courseName, deptId) values (75,'Youth Work',8);
insert into course (id, courseName, deptId) values (76,'Cyber Security',5);
