
/* Insertions for table student */

insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (1,'Guadalupe','Donoghue','8483 Adams St.','','Elgin','IL','60120',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (2,'Raye','Selig','7731 Jockey Hollow Street','','Somerset','NJ','08873',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (3,'Vivien','Ragusa','35 W. Spring Lane','','Vienna','VA','22180',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (4,'Georgette','Darcy','202A El Dorado St.','','Rockaway','NJ','07866',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (5,'Mui','Toller','814 Nicolls Ave.','','Cumberland','RI','02864',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (6,'Sunny','Loveless','7292 Squaw Creek St.','','Mcallen','TX','78501',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (7,'France','Bissonette','9372 Walnutwood Drive','Apt 73','Circle Pines','MN','55014',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (8,'Spring','Pekar','55 West Bridgeton Ave.','','Commack','NY','11725',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (9,'Emmett','Gilbride','9 N. Hudson Lane','','Newburgh','NY','12550',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (10,'Mi','Raiford','27 Devon St.','','Centreville','VA','20120',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (11,'Russel','Neloms','74 Hartford St.','','Hummelstown','PA','17036',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (12,'Odilia','Gilkison','619 South Grand Street','','Culpeper','VA','22701',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (13,'Lili','Gran','29 East Helen St.','','New Milford','CT','06776',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (14,'Tiffaney','Grantham','8319 Lees Creek St.','','Framingham','MA','01701',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (15,'Kesha','Hurdle','387 Church Drive','','Sykesville','MD','21784',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (16,'Camellia','Schenck','2 Johnson Avenue','','Temple Hills','MD','20748',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (17,'Mariann','Fiorini','5 Baker Ave.','','Marysville','OH','43040',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (18,'Marcell','Sturdevant','797 Lake View Ave.','','Aliquippa','PA','15001',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (19,'Trinidad','Cusic','8271 Lower River Road','','Nazareth','PA','18064',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (20,'Otilia','Wiener','356 Lyme Avenue','','San Antonio','TX','78213',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (21,'Maryellen','Maybee','8815 Bradford Ave.','','Cary','NC','27511',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (22,'Lorilee','Frenz','7 Canal Street','','Muskegon','MI','49441',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (23,'Marcela','Ortez','7655 Strawberry St.','','Ottawa','IL','61350',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (24,'Cassey','Pizzuto','88 Crescent Drive','','New Bedford','MA','02740',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (25,'Denis','Kriger','7613 Clark Avenue','','Mooresville','NC','28115',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (26,'Cathleen','Woolfolk','9210 Blackburn Dr.','','Merrimack','NH','03054',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (27,'Wilson','Chason','776 Locust Ave.','','North Wales','PA','19454',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (28,'Leandro','Irwin','60 El Dorado Road','','Mason','OH','45040',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (29,'Nathalie','Hur','934 West Fairway St.','','Hoboken','NJ','07030',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (30,'Shaquita','Ronan','325 W. Jefferson Road','','Clementon','NJ','08021',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (31,'Lydia','Regan','5 Evergreen Rd.','','Akron','OH','44312',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (32,'Cicely','Moye','7945 Fairground Ave.','','Braintree','MA','02184',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (33,'Babara','Felker','8111 Oak Meadow St.','','Danville','VA','24540',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (34,'Marylin','Starkweather','179 Leatherwood St.','','Philadelphia','PA','19111',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (35,'Marilou','Holleman','28 Maple Lane','','Cedar Falls','IA','50613',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (36,'Eleanor','Sottile','9 Lancaster Drive','','Davison','MI','48423',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (37,'Towanda','Fedor','631 Carson Ave.','','Meriden','CT','06450',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (38,'Rheba','Rampton','378 Silver Spear Drive','','Cary','NC','27511',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (39,'Carmella','Caicedo','89 Green St.','','Framingham','MA','01701',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (40,'Delphine','Staub','9809 N. Rockledge Avenue','','San Lorenzo','CA','94580',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (41,'Earleen','Mcclanahan','48 Fieldstone Drive','','Hollis','NY','11423',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (42,'Kacey','Iannotti','99 Newbridge Ave.','','Pleasanton','CA','94566',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (43,'Johana','Jolley','5 North Walnutwood Drive','','Upper Darby','PA','19082',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (44,'Kali','Distefano','468 East Pin Oak St.','','Wilmette','IL','60091',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (45,'Brande','Tinney','816 Creek Drive','','Morristown','NJ','07960',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (46,'Trenton','Fling','859 Hill Street','','Lake Zurich','IL','60047',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (47,'Roni','Madry','9944 Silver Spear Street','','Opa Locka','FL','33054',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (48,'Lynnette','Luck','733 Johnson St.','','Navarre','FL','32566',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (49,'Dorothy','Cornette','9290 Whitemarsh Dr.','','Fernandina Beach','FL','32034',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (50,'Britta','Kittle','7540 West Mill Road','','Gallatin','TN','37066',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (51,'Weldon','Gillham','8899 Sherwood St.','','Hephzibah','GA','30815',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (52,'Jodie','Omara','2 Stillwater Court','','Blackwood','NJ','08012',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (53,'Hermine','Tollison','948 Bridgeton Ave.','','Saint Joseph','MI','49085',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (54,'Emely','Wooley','15 Wagon Drive','','Dorchester','MA','02125',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (55,'Aurea','Olmos','241 Beach Street','','Fairport','NY','14450',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (56,'Isobel','Caddy','52 Country Lane','','Myrtle Beach','SC','29577',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (57,'Rudolph','Litchfield','7601 S. Armstrong Street','','Phoenixville','PA','19460',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (58,'Bernardo','Bivens','27 Philmont Ave.','','Hollywood','FL','33020',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (59,'Clarine','Dunleavy','4 Logan Ave.','','Medina','OH','44256',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (60,'Albertina','Hirsh','1 Westminster Dr.','','Redford','MI','48239',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (61,'Lucile','Murrell','9155 Peninsula Ave.','','Marion','NC','28752',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (62,'Rudy','Lanoue','930 Green Hill Ave.','','North Augusta','SC','29841',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (63,'Nisha','Shover','172 Hilldale Drive','','Saint Cloud','MN','56301',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (64,'Casie','Bevilacqua','9 Hawthorne Ave.','','Murfreesboro','TN','37128',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (65,'Heidi','Tetrault','7984 Overlook Street','','Oviedo','FL','32765',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (66,'Rosena','Kulinski','19 Ketch Harbour St.','','Forney','TX','75126',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (67,'Alanna','Kimbrell','46 NW. Swanson Dr.','','Trenton','NJ','08610',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (68,'Rheba','Sgro','7180 Edgemont Ave.','','Panama City','FL','32404',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (69,'Oren','Guyette','249 Cherry Rd.','','New Bern','NC','28560',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (70,'Mollie','Gassert','618 Vermont Drive','','Rocklin','CA','95677',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (71,'Jill','Carothers','88 Colonial St.','','Saugus','MA','01906',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (72,'Trudi','Birkholz','651 Marsh Dr.','','Fleming Island','FL','32003',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (73,'Keturah','Mchargue','563 West Walnutwood St.','','Holland','MI','49423',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (74,'Arica','Grahn','7805 N. Old York Dr.','','West Des Moines','IA','50265',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (75,'Everette','Jasmin','696 Nicolls Lane','','Glastonbury','CT','06033',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (76,'Kiera','Deegan','8585 Heritage Dr.','','New Lenox','IL','60451',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (77,'Nick','Steel','5 E. Johnson Street','','Hamtramck','MI','48212',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (78,'Indira','Madison','88 W. Pineknoll St.','','Teaneck','NJ','07666',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (79,'Tifany','Borrego','7440 Ridgewood Street','','Fort Washington','MD','20744',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (80,'Criselda','Casanova','215 Swanson St.','','Bangor','ME','04401',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (81,'Alla','Bruck','37 Mammoth Lane','','Carrollton','GA','30117',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (82,'Johnathan','Binger','8342 North Snake Hill Ave.','','Cedar Rapids','IA','52402',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (83,'Elaina','Alers','9826 Harvard Ave.','','Honolulu','HI','96815',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (84,'Malissa','Mcdonalds','8916 Rock Creek St.','','Chattanooga','TN','37421',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (85,'Sarai','Orloff','7626 Hall Dr.','','Onalaska','WI','54650',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (86,'Wilhelmina','Mcauliffe','559 North Jefferson Drive','','Hartselle','AL','35640',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (87,'Otis','Bellew','23 Meadow St.','','Cuyahoga Falls','OH','44221',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (88,'Twana','Plantz','802 Orange Court','','East Stroudsburg','PA','18301',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (89,'Kelvin','Devore','58 Pennsylvania Avenue','','Northville','MI','48167',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (90,'Lillia','Bier','567 6th St.','','Twin Falls','ID','83301',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (91,'Exie','Lapointe','350 Buckingham Rd.','','Savage','MN','55378',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (92,'Chung','Bigley','6 New Road','','Hammonton','NJ','08037',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (93,'Mike','Malave','9977 W. Amerige Street','','Southington','CT','06489',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (94,'Karon','Mobley','11 East Glenlake St.','','Winter Garden','FL','34787',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (95,'Herminia','Hemingway','9546 Hartford Drive','','Hillsborough','NJ','08844',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (96,'Antoinette','Bowen','561 Rockland St.','','Havertown','PA','19083',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (97,'Brande','Windley','48 Amherst Drive','','Carol Stream','IL','60188',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (98,'Guy','Shill','86 Pendergast Dr.','','Hamburg','NY','14075',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (99,'Necole','Winebarger','321 Durham Lane','','Woburn','MA','01801',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (100,'Dia','Wolski','97 W. Cemetery Drive','Apt 726','New Castle','PA','16101',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (101,'Zella','Toussaint','260 Constitution Drive','','Ozone Park','NY','11417',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (102,'Yon','Rivet','435 Valley View Drive','','Southfield','MI','48076',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (103,'Shanta','Everitt','211 W. Academy St.','','Andover','MA','01810',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (104,'Jamison','Watford','9086 Gulf St.','','Duarte','CA','91010',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (105,'Marget','Sober','64 Gonzales Dr.','','Buford','GA','30518',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (106,'Blondell','Loffredo','32 College Road','','New Britain','CT','06051',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (107,'Ping','Gibb','64 Bradford Drive','','Fuquay Varina','NC','27526',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (108,'Arnette','Rancourt','8342 Lincoln Lane','','Rossville','GA','30741',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (109,'Charissa','Swinney','9180 Glen Eagles Ave.','','Milwaukee','WI','53204',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (110,'Lura','Atilano','622 Hickory St.','','Middletown','CT','06457',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (111,'Valeria','Vetrano','20 Gulf St.','','Bethlehem','PA','18015',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (112,'Chantell','Seago','346 6th Avenue','','Sterling','VA','20164',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (113,'Reinaldo','Salerno','7023 Cottage Circle','','Maineville','OH','45039',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (114,'Lolita','Beals','84 Bellevue Avenue','','Goodlettsville','TN','37072',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (115,'Marcene','Eggleston','929 Grand Street','','Asheville','NC','28803',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (116,'Kasie','Stott','7422 Aspen Street','','Baltimore','MD','21206',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (117,'Jennie','Perlmutter','7410 West Mill Dr.','','Point Pleasant Beach','NJ','08742',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (118,'Jim','Lambrecht','59 Orange Drive','','Bradenton','FL','34203',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (119,'Adelia','Rew','794 Birchpond Street','','Independence','KY','41051',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (120,'Jana','Inoue','2 Madison Ave.','','Yonkers','NY','10701',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (121,'Nga','Rankin','644 Sulphur Springs St.','','Biloxi','MS','39532',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (122,'Emerita','Gomes','957 Jackson St.','','Hernando','MS','38632',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (123,'Tierra','Dykes','7928 Cambridge Ave.','','Port Saint Lucie','FL','34952',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (124,'Marjory','Kamer','815 South Fulton Avenue','','Norwich','CT','06360',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (125,'Sarita','Jeon','77 Armstrong Street','','Westerville','OH','43081',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (126,'Katlyn','Henrichs','690 Essex Street','','Saint Cloud','MN','56301',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (127,'Jonelle','Baskin','69 Pulaski Lane','','Piqua','OH','45356',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (128,'Eloise','Suter','7518 West Nut Swamp Drive','','Huntsville','AL','35803',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (129,'Sharilyn','Chmura','64 Rosewood Drive','','Savannah','GA','31404',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (130,'Zachery','Flores','8993 Lincoln St.','','Chicago','IL','60621',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (131,'Fredda','Utley','384 Rockcrest Court','','Royersford','PA','19468',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (132,'Israel','Eisenstein','54 W. 8th St.','','Glendale','AZ','85302',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (133,'Twanda','Towsend','8332 South Cottage Dr.','','Hempstead','NY','11550',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (134,'Sigrid','Cardwell','57 St Louis Dr.','','Chelsea','MA','02150',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (135,'Vida','Stubbs','52 SW. Ohio Ave.','','Dothan','AL','36301',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (136,'Elroy','Chynoweth','529 NW. Mulberry Lane','','Maplewood','NJ','07040',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (137,'Chet','Uber','778 Carriage Street','','Middle River','MD','21220',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (138,'Mai','Leonardo','8587 E. Lyme St.','','Haines City','FL','33844',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (139,'Mercy','Meas','883 Bridgeton St.','','Kennewick','WA','99337',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (140,'Maricruz','Redmond','9 Trenton St.','','Lake Jackson','TX','77566',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (141,'Leeanna','Theiss','8988 Addison Ave.','','Flowery Branch','GA','30542',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (142,'Jeanie','Stefani','87 Newcastle Dr.','','Yuma','AZ','85365',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (143,'Claudia','Barclay','9372 North Pulaski Road','','Decatur','GA','30030',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (144,'Keshia','Judon','7364 Carson St.','','Miamisburg','OH','45342',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (145,'Farah','Stovall','8723 Gartner St.','','Butte','MT','59701',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (146,'Sonya','Nell','7278 Fulton Ave.','','Franklin Square','NY','11010',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (147,'Ada','Caul','712 Ohio Ave.','','Rockville','MD','20850',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (148,'Zora','Garrison','7294 North Manchester Dr.','','Lexington','NC','27292',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (149,'Lezlie','Godina','770 Oak Meadow Ave.','','West Chester','PA','19380',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (150,'Dustin','Malchow','8837 N. Arlington Drive','','Westerville','OH','43081',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (151,'Retta','Saunders','35 E. Pineknoll Ave.','','Columbus','GA','31904',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (152,'Ardelle','Vining','22 Cleveland Lane','','Cranberry Twp','PA','16066',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (153,'Renna','Shedd','7385 West Rockcrest St.','','New Bedford','MA','02740',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (154,'Krystle','Kerfien','9285 Bellevue Street','','South Richmond Hill','NY','11419',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (155,'Adelaide','Coonrod','47 Van Dyke Avenue','','Traverse City','MI','49684',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (156,'Carisa','Brewton','34 Shadow Brook Avenue','','Boynton Beach','FL','33435',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (157,'Corie','Garza','8491 N. Addison St.','','Frankfort','KY','40601',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (158,'January','Coons','13 Cooper St.','','Memphis','TN','38106',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (159,'Nedra','Hauser','52 Buckingham Rd.','','Lincoln','NE','68506',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (160,'Hyacinth','Slankard','272 Cedar Ave.','','Knoxville','TN','37918',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (161,'Floyd','Lykins','8293 Mayfair Drive','','Basking Ridge','NJ','07920',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (162,'Elke','Sheperd','163 West St.','','Santa Clara','CA','95050',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (163,'Nichole','Greear','587 Selby St.','','Vienna','VA','22180',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (164,'Bao','Belford','22 Railroad Dr.','','Kansas City','MO','64151',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (165,'Randa','Hem','487 East Colonial Lane','','Floral Park','NY','11001',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (166,'Gearldine','Veith','885 Rocky River Ave.','','Suffolk','VA','23434',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (167,'Wilburn','Accardo','58 Randall Mill Ave.','','Metairie','LA','70001',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (168,'Jina','Hemminger','932 North Saxton Drive','','Union City','NJ','07087',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (169,'Stepanie','Gephart','605C Lakeview Road','','Willoughby','OH','44094',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (170,'Shelby','Cotner','3 Kirkland St.','','Ossining','NY','10562',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (171,'Heath','Burkart','8415 Canal Court','','Avon','IN','46123',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (172,'Cathrine','Pinkett','967 Logan Street','','Addison','IL','60101',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (173,'Mica','Earley','7981 South Beacon Rd.','','Lincoln','NE','68506',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (174,'Marilynn','Daigneault','8972 Prince Dr.','','Elk River','MN','55330',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (175,'Jone','Nicely','35 Gates Ave.','','Palm Beach Gardens','FL','33410',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (176,'Chae','Stiller','318 Fairground Street','','Norwich','CT','06360',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (177,'Ira','Letendre','90 Lakewood St.','','Atwater','CA','95301',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (178,'Kassandra','Carrier','9768 North William Ave.','','New Hyde Park','NY','11040',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (179,'Rosie','Centeno','93 Cardinal Drive','','Hightstown','NJ','08520',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (180,'Kassie','Lanphere','368 Rockwell Street','','Beloit','WI','53511',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (181,'Lynsey','Santillanes','442 Hall Rd.','','Owensboro','KY','42301',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (182,'Keenan','Washburn','1 Cedar Swamp Drive','','Lombard','IL','60148',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (183,'Ashlie','Laclair','7329 Homestead Ave.','','Hicksville','NY','11801',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (184,'Alta','Dennis','7124 N. Front Drive','','Chattanooga','TN','37421',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (185,'Gabrielle','Basel','8626 Lake View Street','','Phillipsburg','NJ','08865',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (186,'Barbra','Farwell','7708 Oakwood St.','','Satellite Beach','FL','32937',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (187,'Quiana','Thompson','7874 Jefferson Rd.','','Baldwin','NY','11510',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (188,'Roxanne','Kuehne','97 Marvon Street','','Oak Lawn','IL','60453',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (189,'Casandra','Feltmann','138 Peninsula Road','','Superior','WI','54880',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (190,'Sueann','Wagner','9610 Rockcrest Court','','San Pablo','CA','94806',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (191,'Garth','Knaus','9055 W. Winchester Road','','Fort Lauderdale','FL','33308',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (192,'Freida','Banvelos','190 Military Rd.','','Upper Marlboro','MD','20772',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (193,'Camille','Chauez','7386 Church Rd.','','Warren','MI','48089',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (194,'Shayna','Mccluney','768 Hall Street','','Mason','OH','45040',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (195,'Jeanetta','Hilaire','36 Miles Ave.','','Lansdowne','PA','19050',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (196,'Malika','Perreira','1 Depot St.','','Fort Mill','SC','29708',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (197,'Jesse','Lowrance','3 University Lane','','Atwater','CA','95301',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (198,'Faviola','Malm','37 La Sierra St.','','Glastonbury','CT','06033',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (199,'Laurena','Wydra','361 Taylor Road','','Deltona','FL','32725',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (200,'Chet','Ditmore','7798 Goldfield St.','','Hudsonville','MI','49426',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (201,'Lyman','Cumbo','450 Beech Lane','','Des Moines','IA','50310',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (202,'Kathey','Miner','727 Miles Dr.','','Wethersfield','CT','06109',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (203,'Leonore','Summerville','511 Beach Rd.','','Waterloo','IA','50701',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (204,'Angla','Clukey','8588 Whitemarsh Ave.','','Champaign','IL','61821',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (205,'Dorene','Warlick','906 Kirkland Street','','Bowling Green','KY','42101',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (206,'Kerrie','Hayne','68 Cooper Court','','Rock Hill','SC','29730',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (207,'Zella','Acklin','67 Windsor St.','','Lithonia','GA','30038',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (208,'Charlsie','Falcone','8779 Hawthorne Street','','Chesterfield','VA','23832',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (209,'Marlyn','Segers','3 Pheasant Lane','','Cape Coral','FL','33904',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (210,'Natalya','Luebke','568 South Thomas Street','','Inman','SC','29349',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (211,'Tiffani','Hillsman','9552 Swanson St.','','West Roxbury','MA','02132',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (212,'Patience','Hofer','224 Wilson St.','','Centreville','VA','20120',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (213,'Rodrigo','Marzette','823 Miles Dr.','','Newton','NJ','07860',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (214,'Eboni','Watt','400 Edgemont St.','','Winona','MN','55987',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (215,'Marissa','Kuck','43 Blackburn Avenue','','Conway','SC','29526',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (216,'Tristan','Magnani','797 Lake Forest St.','','Whitehall','PA','18052',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (217,'Loura','Vise','93 Grove St.','','Port Orange','FL','32127',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (218,'Griselda','Orwig','8248 Heritage Ave.','','Bloomington','IN','47401',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (219,'Maranda','Bobadilla','71 Glenwood St.','','Deltona','FL','32725',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (220,'Pauline','Woodberry','8892 Shore St.','','Olney','MD','20832',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (221,'Fernanda','Leet','19 High Ridge Rd.','','Wantagh','NY','11793',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (222,'Randi','Hoglund','8168 Green Street','','Randallstown','MD','21133',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (223,'Lorriane','Viloria','806 South Eagle Avenue','','Rockledge','FL','32955',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (224,'Vincenza','Robin','47 North Harvard St.','','Akron','OH','44312',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (225,'Micheal','Liberatore','206 Morris Ave.','','Ocean Springs','MS','39564',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (226,'Marion','Glass','13 Ocean Ave.','','Warren','MI','48089',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (227,'Johanne','Bacote','21 SW. Richardson Street','','Englewood','NJ','07631',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (228,'Jeannette','Kleckner','22 N. Hartford St.','','Schaumburg','IL','60193',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (229,'Avril','Marshburn','439 Amherst St.','','Dickson','TN','37055',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (230,'Shawnna','Kiddy','622 Ashley Drive','Apt 35','Zeeland','MI','49464',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (231,'Samual','Petty','772 S. Myrtle St.','','Evanston','IL','60201',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (232,'Jo','Buechner','7225B Henry St.','','Great Falls','MT','59404',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (233,'Henry','Demery','9223 Smith Store Drive','','Bay Shore','NY','11706',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (234,'Sallie','Granderson','52 Alderwood Avenue','','Hartselle','AL','35640',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (235,'Valeria','Vassel','442 Miller St.','','Naugatuck','CT','06770',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (236,'Georgene','Wadkins','295 Leatherwood Street','','Boston','MA','02127',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (237,'Ilse','Persing','191 Central Dr.','','Starkville','MS','39759',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (238,'Weldon','Philbrook','900 West Golf Street','','Monroeville','PA','15146',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (239,'Debera','Butner','752 Halifax St.','','Loveland','OH','45140',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (240,'Tara','Hubbs','291 Cactus Court','','Maryville','TN','37803',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (241,'Arline','Lisowski','8346 East New Saddle St.','','Olympia','WA','98512',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (242,'Bryce','Honea','8 Bohemia Street','','Millville','NJ','08332',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (243,'Maisie','Guel','849 Durham Street','','Fort Lauderdale','FL','33308',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (244,'Garrett','Chasse','4 N. Garfield Lane','','Whitestone','NY','11357',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (245,'Julius','Bertsch','46 Vernon Dr.','','Nazareth','PA','18064',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (246,'Lisbeth','Gamet','8360 Pulaski St.','','Branford','CT','06405',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (247,'Ruthanne','Petersen','7390 Cactus St.','','Neptune','NJ','07753',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (248,'Dante','Fabrizio','11 Winding Way Rd.','','Amityville','NY','11701',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (249,'Colene','Shupp','7263 Longfellow Street','','Bridgewater','NJ','08807',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (250,'Alia','Stenson','7997 Cemetery Ave.','','Aiken','SC','29803',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (251,'Davida','Vanpelt','9274 Greystone Avenue','','Moses Lake','WA','98837',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (252,'Maxine','Restivo','287 West Shub Farm Rd.','','Carol Stream','IL','60188',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (253,'Cathey','Groom','552 Hill Field Street','','Merrillville','IN','46410',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (254,'Bertha','Callas','8830 Longfellow Drive','','Loganville','GA','30052',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (255,'Suzy','Start','863 Pierce Street','','Holland','MI','49423',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (256,'Wiley','Horvath','770 Pin Oak Lane','','Newport News','VA','23601',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (257,'Reyes','Fackler','7501 Fifth Ave.','','Dublin','GA','31021',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (258,'Len','Kong','893 3rd Ave.','','Bensalem','PA','19020',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (259,'Bret','Marino','661 Augusta Court','','Warren','MI','48089',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (260,'Yvonne','Mcconville','391 Bridge Court','','Dayton','OH','45420',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (261,'Lorena','Rooney','4 Plumb Branch Dr.','','New Rochelle','NY','10801',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (262,'Edyth','Trostle','463B South Queen Lane','','Harleysville','PA','19438',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (263,'Phoebe','Gonce','7922 East Ave.','','Bloomfield','NJ','07003',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (264,'Carmon','Rosenzweig','7475 Bayport Street','','Orlando','FL','32806',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (265,'Neely','Kwiatkowski','9024 York Road','','Leominster','MA','01453',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (266,'Min','Macias','60 Lakeshore Ave.','','Ballston Spa','NY','12020',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (267,'Ima','Wolter','8458 Randall Mill Ave.','','Auburndale','FL','33823',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (268,'Willene','Upton','2 Constitution Ave.','','Woodhaven','NY','11421',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (269,'Aurora','Mcentire','395 Lancaster St.','','Palm Beach Gardens','FL','33410',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (270,'Jackeline','Villalba','14 Arcadia St.','','Cheshire','CT','06410',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (271,'Lizzie','Kollar','86 Border Street','','New Kensington','PA','15068',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (272,'Debrah','Burrus','738 Wilson St.','','Cincinnati','OH','45211',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (273,'Linnie','Lieberman','905 West Marshall Ave.','','Rockledge','FL','32955',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (274,'Irish','Theroux','933 Hill Lane','','Elmont','NY','11003',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (275,'Sulema','Crass','789 Belmont Ave.','','Marysville','OH','43040',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (276,'Malka','Darrow','306 Heritage Ave.','','Clayton','NC','27520',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (277,'Martin','Condit','90 Silver Spear Road','','Evansville','IN','47711',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (278,'Avery','Stayton','98 High Ridge Street','','Rocky Mount','NC','27804',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (279,'Aubrey','Larochelle','655 Lakeview St.','','Ponte Vedra Beach','FL','32082',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (280,'Bob','Spray','8108 Peninsula Rd.','','Meadville','PA','16335',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (281,'Tawny','Popham','8440 Bishop St.','','Gaithersburg','MD','20877',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (282,'Nannette','Feaster','30 Roberts Lane','','Camden','NJ','08105',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (283,'Dedra','Raybon','45 Illinois St.','','Alexandria','VA','22304',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (284,'Tran','Holm','129 York Drive','','Roy','UT','84067',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (285,'Gino','Marano','13 Vernon Lane','','Valrico','FL','33594',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (286,'Joya','Lasker','865 Surrey Rd.','','Banning','CA','92220',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (287,'Jona','Seaman','171 North Bear Hill Ave.','','Cumberland','RI','02864',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (288,'Ena','Beckel','92 West Westport Street','','Onalaska','WI','54650',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (289,'Ivonne','Pappan','15 Lakewood Court','','New Bedford','MA','02740',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (290,'Delcie','Muth','8523 Bohemia Street','','Goose Creek','SC','29445',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (291,'Maribeth','Semon','28 Highland St.','','New Rochelle','NY','10801',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (292,'Allan','Paulette','844 Edgewood Ave.','','Grand Blanc','MI','48439',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (293,'Angeles','Lamont','79 Nut Swamp Circle','','Largo','FL','33771',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (294,'Eddy','Banister','7450 Race Street','','Acworth','GA','30101',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (295,'Shaunta','Micco','9065 West Mountainview Street','','Dearborn','MI','48124',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (296,'France','Daoust','723 West Valley St.','','Brockton','MA','02301',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (297,'Rosita','Laporte','9991 South Griffin Street','','Pottstown','PA','19464',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (298,'Nancie','Mealer','64 Rockledge Ave.','','Maplewood','NJ','07040',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (299,'Jeremiah','Ostrowski','7814 Peg Shop St.','','Taunton','MA','02780',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (300,'Maximina','Moe','87 Fifth Street','','Boynton Beach','FL','33435',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (301,'Leonardo','Baldwin','803 Blackburn Lane','','New York','NY','10002',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (302,'Rodolfo','Galipeau','9 North Park Avenue','','Rossville','GA','30741',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (303,'Fernanda','Louden','7497 Prince Ave.','','Flint','MI','48504',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (304,'Clair','Brezinski','9348 8th Street','','New Hyde Park','NY','11040',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (305,'Rolande','Gunnels','37 Wall St.','','Tupelo','MS','38801',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (306,'Maye','Gullette','82 South State Dr.','','Minot','ND','58701',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (307,'Antonetta','Mund','8634 Fairground Road','','Westerville','OH','43081',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (308,'Lauralee','Harlin','356 Linden St.','','Pleasanton','CA','94566',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (309,'Alline','Creager','55 Lawrence Court','','Cumberland','RI','02864',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (310,'Camellia','Razor','411 1st St.','','Carrollton','GA','30117',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (311,'Kayleen','Merriweather','24 Amerige Dr.','','Doylestown','PA','18901',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (312,'Richard','Pina','7464 Mayfair St.','','Hopkins','MN','55343',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (313,'Mimi','Dozal','9409 Amherst Court','','Jacksonville','NC','28540',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (314,'Alonzo','Licht','821 Princeton Street','','Chelmsford','MA','01824',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (315,'Brock','Hafer','44 Border Lane','','East Orange','NJ','07017',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (316,'Loretta','Denmark','9428 Cactus Ave.','','Calhoun','GA','30701',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (317,'Theresa','Stmarie','425 Oxford Dr.','','Paducah','KY','42001',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (318,'Marlys','Kivi','8013 N. Garfield Street','','Vienna','VA','22180',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (319,'Shandra','Gochenour','85 Second Dr.','','Bridgeport','CT','06606',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (320,'Mendy','Harrah','708 Richardson St.','','Macon','GA','31204',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (321,'Nathalie','Hudock','75 Creekside Ave.','','Granger','IN','46530',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (322,'Genna','Cullum','9909 W. Border Drive','','East Stroudsburg','PA','18301',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (323,'Kristen','Catalan','84 Warren St.','','Onalaska','WI','54650',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (324,'Teri','Hartzler','94 South Blackburn Ave.','','Pikesville','MD','21208',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (325,'Jasmin','Shadduck','4 Shirley Ave.','','Ashland','OH','44805',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (326,'Jeff','Sabala','58 Tailwater Avenue','','Bradenton','FL','34203',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (327,'Donald','Rose','9997 Cactus Dr.','','Teaneck','NJ','07666',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (328,'Emelina','Boddy','184 Henry St.','','Belleville','NJ','07109',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (329,'Kathline','Trowell','90 E. Coffee Ave.','','La Vergne','TN','37086',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (330,'Kevin','Bohland','23 Bow Ridge St.','','Victoria','TX','77904',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (331,'Paige','Petitt','5 Newbridge St.','','Chattanooga','TN','37421',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (332,'Rowena','Trembley','9111 North Saxton Street','','Harrison Township','MI','48045',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (333,'Adan','Dabbs','56 Summerhouse Street','','Amsterdam','NY','12010',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (334,'Chance','Buscher','18 South Heather Drive','','Terre Haute','IN','47802',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (335,'Myrtie','Karnes','53 Cambridge Lane','','Pasadena','MD','21122',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (336,'Carlie','Nodal','9574 Pendergast Court','','Ottumwa','IA','52501',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (337,'Keira','Laudenslager','8196 Cherry Hill Dr.','','Englishtown','NJ','07726',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (338,'Lakeesha','Schrock','29 Depot Ave.','','Elmhurst','NY','11373',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (339,'Kristal','Mclester','99 N. Cobblestone Rd.','','Antioch','TN','37013',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (340,'Joan','Tena','800 NE. Manor Station Court','','Marshalltown','IA','50158',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (341,'Tori','Marrinan','630 S. Railroad Ave.','','Bakersfield','CA','93306',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (342,'Evan','Mccary','874 Marshall Rd.','','Washington','PA','15301',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (343,'Krysta','Fullen','9923 Peninsula Avenue','','Perth Amboy','NJ','08861',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (344,'Alan','Demartino','77 Heather St.','','Woodside','NY','11377',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (345,'Hoyt','Matheny','7259 Harrison Street','','Derby','KS','67037',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (346,'Ricky','Cantwell','7260 S. Dunbar Court','','Leland','NC','28451',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (347,'Caterina','Mccrory','7541 South Bradford Ave.','','Hopewell','VA','23860',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (348,'Tracy','Allin','8876 Glenlake Street','','Parsippany','NJ','07054',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (349,'Naida','Sheppard','2 Main St.','','Smithtown','NY','11787',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (350,'Caryn','Abdallah','728 Silver Spear Ave.','','Passaic','NJ','07055',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (351,'Kirstie','Basile','7450 Border St.','','Casselberry','FL','32707',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (352,'Ronny','Dublin','948 Warren Dr.','','Port Richey','FL','34668',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (353,'Taneka','Matula','746 Philmont Drive','Suite 5','Murfreesboro','TN','37128',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (354,'Kera','Wemple','224 William St.','','Clover','SC','29710',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (355,'Tarra','Watt','51 East Glen Creek Ave.','','Brandon','FL','33510',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (356,'Barbra','Seo','484 School Rd.','','Logansport','IN','46947',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (357,'Aretha','Turnipseed','19 Glen Creek St.','','Mansfield','MA','02048',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (358,'Chara','Renegar','7147 Arlington Drive','','Mokena','IL','60448',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (359,'Edda','Patnode','7527 East Brandywine Ave.','','Central Islip','NY','11722',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (360,'Kenny','Sheffler','61 Devonshire Lane','','Schererville','IN','46375',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (361,'Francisca','Fielden','481 Beacon Dr.','','Peabody','MA','01960',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (362,'Val','Rosebrook','343 Pierce Road','','Princeton','NJ','08540',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (363,'Rolanda','Binder','8763 Stonybrook St.','','Gloucester','MA','01930',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (364,'Sylvia','Darwin','28 West Clinton Dr.','','Park Ridge','IL','60068',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (365,'Mariano','Meaders','8373 Pendergast Ave.','','Asbury Park','NJ','07712',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (366,'Yuriko','Krizan','51 Grand St.','','Ridgefield','CT','06877',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (367,'Cristal','Montalbano','210 Euclid Lane','','Vineland','NJ','08360',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (368,'Ron','Ottman','829 N. Hamilton Dr.','','Lawrence Township','NJ','08648',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (369,'Conchita','Leonhardt','8 Riverside Rd.','','Hamtramck','MI','48212',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (370,'Kelsi','Ketterman','8825 Prince Drive','','Elkhart','IN','46514',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (371,'Venessa','Peppard','350 Shub Farm Street','','Fenton','MI','48430',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (372,'Yelena','Clair','82 Linda St.','','Woodhaven','NY','11421',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (373,'Grisel','Batchelor','9640 Wakehurst Lane','','Southaven','MS','38671',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (374,'Alison','Goza','5 North Hilldale Street','','Bay Shore','NY','11706',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (375,'Willodean','Schnieders','7764 Swanson Lane','','Santa Cruz','CA','95060',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (376,'Tyra','Haymon','7449 Virginia Street','','Yakima','WA','98908',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (377,'Samantha','Ostendorf','8943 West Hickory St.','','Mason City','IA','50401',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (378,'Maranda','Armand','373 Harrison Drive','','Tonawanda','NY','14150',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (379,'Frederic','Carnegie','345 Bear Hill Ave.','','Roslindale','MA','02131',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (380,'Vena','Krohn','2 Golf St.','','Oviedo','FL','32765',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (381,'Carleen','Speakman','78 Del Monte Street','','Raleigh','NC','27603',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (382,'Maximo','Engleman','72 S. Lakeview St.','','Cleveland','TN','37312',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (383,'Tiera','Clever','9031 Academy Road','','Hackensack','NJ','07601',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (384,'Alene','Storie','7809 East Clark Drive','','Amityville','NY','11701',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (385,'Sammie','Lan','361 Pennington Dr.','','Alexandria','VA','22304',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (386,'Sierra','Mayhan','25 Birch Hill Court','','Anderson','SC','29621',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (387,'Shin','Shack','132 Cleveland Drive','','Natick','MA','01760',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (388,'Robena','Levitt','683 North Carpenter Road','','Royal Oak','MI','48067',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (389,'Dolly','Aubin','9865 Selby Ave.','','Bay City','MI','48706',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (390,'Lonna','Crispin','53 Gregory Ave.','','Willoughby','OH','44094',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (391,'Antony','Chess','7155 North Hill St.','','Southgate','MI','48195',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (392,'Donnie','Fewell','1 Liberty Street','','Shelton','CT','06484',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (393,'Chery','Blane','7665 Bow Ridge Street','','Ada','OK','74820',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (394,'Marlena','Schrum','658 W. Sherman Court','','Wallingford','CT','06492',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (395,'Joyce','Hagemann','763 Meadow Street','','Baton Rouge','LA','70806',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (396,'Cinthia','Situ','8334 Pleasant St.','','Manassas','VA','20109',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (397,'Moshe','Basham','39 SE. Hanover Ave.','','Hoffman Estates','IL','60169',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (398,'Ceola','Saver','9730 Dunbar Ave.','','North Haven','CT','06473',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (399,'Allyson','Cockburn','4 Fairview Ave.','','Nanuet','NY','10954',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (400,'Brigette','Rabideau','181 Corona St.','','Northville','MI','48167',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (401,'Shemeka','Nesbitt','8648 Golf Ave.','','Owatonna','MN','55060',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (402,'Gayle','Hawes','11 Clinton Ave.','','Delaware','OH','43015',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (403,'Lanny','Newingham','791 Pacific Rd.','','Saint Joseph','MI','49085',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (404,'Jeniffer','Tanaka','9140 Jefferson Street','','East Hartford','CT','06118',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (405,'Alec','Fankhauser','60 Kirkland St.','','Parkville','MD','21234',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (406,'Jenni','Saleh','880 North Drive','','Onalaska','WI','54650',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (407,'Val','Urso','839 Thompson Lane','','Noblesville','IN','46060',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (408,'Corine','Greening','235 Riverside St.','','Pataskala','OH','43062',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (409,'Adah','Clark','7079 Thomas Ave.','','Freehold','NJ','07728',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (410,'Britt','Brumit','137 Harvey St.','','Wantagh','NY','11793',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (411,'Mozella','Preece','661 Myers St.','','Wheaton','IL','60187',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (412,'Deandra','Seaborn','78 South Street','','Farmington','MI','48331',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (413,'Elly','Doss','391 North Clay Lane','','Lansdale','PA','19446',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (414,'Johnette','Cavender','538 S. Hudson St.','','Kalamazoo','MI','49009',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (415,'Viki','Ma','771 New St.','','North Haven','CT','06473',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (416,'Pattie','Melillo','94 SE. Bald Hill Street','','Hazleton','PA','18201',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (417,'Shawn','Gartman','47 S. Oak Valley Street','','Morton Grove','IL','60053',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (418,'Lois','Loken','6 Buttonwood Court','','Schaumburg','IL','60193',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (419,'Rosario','Varga','85 Helen St.','','Allen Park','MI','48101',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (420,'Ela','Sleeman','75 Brickell St.','','Parkersburg','WV','26101',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (421,'Yang','Brumer','15 Delaware Street','','Banning','CA','92220',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (422,'Francine','Zeiler','8466 Dogwood Dr.','','Conyers','GA','30012',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (423,'Errol','Boland','27 Manor Rd.','','Inman','SC','29349',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (424,'Celina','Quimby','8929 Smith Ave.','','Rosedale','NY','11422',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (425,'Nolan','Rayes','382 Arlington Street','','Bay City','MI','48706',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (426,'Eleonora','Vaden','34 Yukon Drive','','New Albany','IN','47150',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (427,'Fairy','Frier','643 York Ave.','','Nanuet','NY','10954',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (428,'Libbie','Starks','81 Jefferson St.','','Parsippany','NJ','07054',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (429,'Grayce','Bernhard','13 Ketch Harbour St.','','Arlington','MA','02474',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (430,'Emeline','Chivers','898 S. Tanglewood Ave.','','Fort Washington','MD','20744',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (431,'Ava','Steadham','32 SW. Saxon St.','','Oklahoma City','OK','73112',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (432,'Charleen','Doonan','270 Brewery Drive','','Tacoma','WA','98444',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (433,'Ellamae','Lefever','902 Sussex Ave.','','Villa Rica','GA','30180',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (434,'Tad','Gokey','4 Gates Street','','Coram','NY','11727',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (435,'Lashanda','Abdul','792 Glen Ridge Lane','','Baltimore','MD','21206',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (436,'Scarlet','Darr','352 Armstrong Ave.','','Little Falls','NJ','07424',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (437,'Reanna','Fielder','203 West Cottage St.','','Solon','OH','44139',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (438,'Laurette','Orosz','8687 Devonshire St.','','Pataskala','OH','43062',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (439,'Vince','Thoman','75 Green Lake Rd.','','Neenah','WI','54956',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (440,'Logan','Hollingworth','7 Elm St.','','Mays Landing','NJ','08330',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (441,'Houston','Chew','1 Elm Rd.','','Pleasanton','CA','94566',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (442,'Blythe','Delrosario','633 53rd Court','','Ocean Springs','MS','39564',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (443,'Zita','Clemente','35 Westport Drive','','Columbia','MD','21044',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (444,'Rosita','Rickey','540 Wintergreen Drive','','Oakland Gardens','NY','11364',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (445,'Jordan','Bradham','488 Pineknoll Street','','Cedar Rapids','IA','52402',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (446,'Cuc','Mungin','9527 Church Drive','','Houston','TX','77016',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (447,'Salley','Crimmins','9013 Andover St.','','Bemidji','MN','56601',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (448,'Glenna','Zemlicka','439 Wellington Dr.','','Glasgow','KY','42141',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (449,'Judy','Pearse','154 Snake Hill Ave.','','Stillwater','MN','55082',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (450,'Shandra','Camberos','43 Campfire St.','','Wake Forest','NC','27587',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (451,'Hermine','Games','409 Spruce Court','','Westmont','IL','60559',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (452,'Eduardo','Claar','16 SW. Big Rock Cove Street','','Eugene','OR','97402',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (453,'Sonia','Forry','41 West Pierce St.','','Menasha','WI','54952',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (454,'Rolanda','Nichol','8741 Riverview Avenue','','La Porte','IN','46350',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (455,'Marisela','Storlie','441 South Brewery St.','','Murfreesboro','TN','37128',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (456,'Malisa','Ignacio','9075 Littleton Street','','Asbury Park','NJ','07712',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (457,'Carlo','Wiersma','456 Bay Street','','Indiana','PA','15701',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (458,'Mercy','Hemstreet','8 Valley Dr.','','Navarre','FL','32566',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (459,'Ranee','Crosswell','8158 Maiden Ave.','','Maplewood','NJ','07040',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (460,'Leticia','Chipps','9906 West Lookout St.','','Roseville','MI','48066',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (461,'Jonell','Calkins','660 Third Dr.','','Burnsville','MN','55337',8);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (462,'Darcie','Kleis','8093 Cambridge Court','','Racine','WI','53402',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (463,'Cara','Plum','102 Grand Street','','Gwynn Oak','MD','21207',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (464,'Maisha','Navarrete','950 Hartford Lane','','West Des Moines','IA','50265',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (465,'Harriette','Melder','92 NE. Fulton St.','','Ossining','NY','10562',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (466,'Gerda','Battles','345 Ivy Ave.','','Stone Mountain','GA','30083',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (467,'Suk','Geraci','368 N. Myers Street','','Parkville','MD','21234',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (468,'Jenna','Ackles','342 Fawn Rd.','','Des Moines','IA','50310',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (469,'Hoyt','Schmitmeyer','4 Elizabeth Dr.','','Park Forest','IL','60466',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (470,'Maude','Leigh','7887 Lafayette Rd.','','Acworth','GA','30101',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (471,'Darby','Honahni','555 Arcadia Lane','','East Brunswick','NJ','08816',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (472,'Crysta','Kail','7205 Jennings Lane','','Hastings','MN','55033',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (473,'Dedra','Merkel','9531 North Nicolls Lane','','Hollywood','FL','33020',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (474,'Ashlie','Parmentier','699 53rd St.','','Muskogee','OK','74403',4);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (475,'Wilhemina','Waltz','489 Brewery Court','','Butte','MT','59701',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (476,'Shaquita','Marsch','8681 W. Mechanic Court','','Enfield','CT','06082',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (477,'Maybell','Bouldin','28 Summit Street','','Fairburn','GA','30213',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (478,'Lovella','Olmedo','7047 Ketch Harbour St.','','Hillsboro','OR','97124',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (479,'Maryalice','Treat','67 Orange Court','','Fort Mill','SC','29708',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (480,'Shanti','Renfroe','9499 Central St.','','San Antonio','TX','78213',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (481,'Alline','Devers','946 Riverside St.','','Maineville','OH','45039',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (482,'Jene','Sluss','60 Branch St.','','Bethpage','NY','11714',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (483,'Adolph','Pavlik','384 East Canal Rd.','','Norwood','MA','02062',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (484,'Tanya','Devaney','9614 Jefferson Drive','','Lagrange','GA','30240',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (485,'Dominica','Krull','8206 Race Avenue','','Rapid City','SD','57701',7);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (486,'Larry','Han','80 W. Hilldale Drive','','Englewood','NJ','07631',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (487,'Myesha','Mcbay','71 Franklin Ave.','','East Stroudsburg','PA','18301',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (488,'Dolly','Thoms','900 S. Ohio St.','','Rego Park','NY','11374',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (489,'Candis','Hadfield','781 Lilac St.','','Racine','WI','53402',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (490,'Kristan','Teasdale','783 Longbranch St.','','Bonita Springs','FL','34135',1);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (491,'Etha','Stoughton','53 Shady Street','','Irwin','PA','15642',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (492,'Fidel','Wasinger','904 Schoolhouse Court','','Southfield','MI','48076',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (493,'Alexa','Piehl','792 Hanover Street','','Burke','VA','22015',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (494,'Lanette','Klepper','8107 Baker Street','','Plymouth','MA','02360',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (495,'Felix','Due','776 S. Beaver Ridge Drive','','Glenview','IL','60025',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (496,'Margot','Krajewski','61 W. Meadow Street','','Reynoldsburg','OH','43068',2);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (497,'Emmanuel','Grave','9633 Purple Finch St.','','Richardson','TX','75080',3);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (498,'Jessie','Swedberg','50 Hilldale St.','','Brunswick','GA','31525',5);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (499,'Garnet','Bobby','22 Peninsula Street','','Dorchester','MA','02125',6);
insert into student (id,firstname,lastname,street,streetdetail,city,state,postalcode,majorId) values (500,'Gwendolyn','Wentworth','465 Miller Avenue','','Bemidji','MN','56601',8);
